SET IDENTITY_INSERT [dbo].[PharmacologicalGroups] ON
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (1, N'ANESTÉSICOS E ADJUVANTES', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (2, N'ANALGÉSICOS, ANTIPIRÉTICOS E MEDICAMENTOS PARA O ALÍVEIO DA ENXAQUECA', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (3, N'MEDICAMENTOS PARA ALÍVIO DA DOR CRÔNICA', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (4, N'ANTI-INFLAMATÓRIOS E MEDICAMENTOS PARA O TRATAMENTO DA GOTA', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (5, N'ANTIALÉRGICOS E MEDICAMENTOS USADOS EM ANAFILAXIA', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (6, N'ANTI-INFECTANTES', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (7, N'IMUNOSSUPRESSORES E IMUNOTERÁPICOS', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (8, N'MEDICAMENTOS E ANTÍDOTOS USADOS EM INTOXICAÇÕES EXÓGENAS', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (9, N'SOLUÇÕES HIDROELETROLÍTICAS E CORRETORAS DO EQUILÍBRIO ÁCIDO-BÁSICO', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (10, N'AGENTES EMPREGADOS NA TERAPÊUTICA DE NUTRIÇÃO', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (11, N'VITAMINAS E SUBSTÂNCIAS MINERAIS', 1)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (12, N'MEDICAMENTOS QUE ATUAM SOBRE O SISTEMA NERVOSO CENTRAL E PERIFÉRICO', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (13, N'MEDICAMENTOS QUE ATUAM SOBRE O SISTEMA CARDIOVASCULAR E RENAL', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (14, N'MEDICAMENTOS QUE ATUAM SOBRE O SANGUE', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (15, N'MEDICAMENTOS QUE ATUAM SOBRE O SISTEMA DIGESTIVO', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (16, N'MEDICAMENTOS QUE ATUAM SOBRE O SISTEMA RESPIRATÓRIO', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (17, N'MEDICAMENTOS QUE ATUAM SOBRE OS SISTEMAS ENDÓCRINO, REPRODUTOR E URINÁRIO', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (18, N'MEDICAMENTOS UTILIZADOS NO TRATAMENTO/PREVENÇÃO DA OSTEOPOROSE', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (19, N'MEDICAMENTO UTILIZADO NO TRATAMENTO DA DOENÇA DE PAGET', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (20, N'FÁRMACOS USADOS EM PELE, MUCOSAS E FÂNEROS', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (21, N'FÁRMACO UTILIZADO NO TRATAMENTO NA HIPERPLASIA BENIGNA DA PRÓSTATA', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (22, N'RELAÇÃO DE INSUMOS', 2)
INSERT INTO [dbo].[PharmacologicalGroups] ([ID], [Description], [SectionID]) VALUES (23, N'RELAÇÃO DE MEDICAMENTOS DE USO HOSPITALAR', 2)
SET IDENTITY_INSERT [dbo].[PharmacologicalGroups] OFF
